steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'VITE_API_URL=${_VITE_API_URL}'
  - '-f'
  - 'frontend/Dockerfile'
  - '-t'
  - 'gcr.io/$PROJECT_ID/securitypro-frontend:$TAG_NAME'
  - 'frontend'
images:
- 'gcr.io/$PROJECT_ID/securitypro-frontend:$TAG_NAME'